default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  host: localhost
  database: alpha_blog_development

test:
  <<: *default
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  host: localhost
  database: alpha_blog_test

production:
  <<: *default
  database: alpha_blog_production
  username: alpha_blog
  password: <%= ENV["ALPHA_BLOG_DATABASE_PASSWORD"] %>

